<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RuntimeFrameworkVersion>8.0.30</RuntimeFrameworkVersion>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <ApplicationIcon />
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SQCD.Agv.Application/SQCD.Agv.Application.csproj" />
    <ProjectReference Include="../SQCD.Agv.Core/SQCD.Agv.Core.csproj" />
    <ProjectReference Include="../SQCD.Agv.Infrastructure/SQCD.Agv.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
